

export const SET_CHARACTERS_LIST = 'SET_CHARACTERS_LIST';
export const SET_CHARACTERS_LIST_PAGED = 'SET_CHARACTERS_LIST_PAGED';
export const GET_CHARACTERS_LIST = 'GET_CHARACTERS_LIST';
export const GET_CHARACTERS_LIST_PAGED = 'GET_CHARACTERS_LIST_PAGED';

export const GET_CHARACTERS_COMICS_LIST = 'GET_CHARACTERS_COMICS_LIST';
export const GET_CHARACTERS_COMICS_LIST_PAGED = 'GET_CHARACTERS_COMICS_LIST_PAGED';
export const SET_CHARACTERS_COMICS_LIST = 'SET_CHARACTERS_COMICS_LIST';
export const SET_CHARACTERS_COMICS_LIST_PAGED = 'SET_CHARACTERS_COMICS_LIST_PAGED';

export const RESET_CHARACTERS_LIST = 'RESET_CHARACTERS_LIST';
export const RESET_CHARACTERS_COMICS_LIST = 'RESET_CHARACTERS_COMICS_LIST';
