export const SET_ACTUAL_CHARACTER = 'SET_ACTUAL_CHARACTER';
export const SET_ACTUAL_CHARACTER_COMICS = 'SET_ACTUAL_CHARACTER_COMICS';
export const SET_CHARACTERS_LIST = 'SET_CHARACTERS_LIST';
export const GET_CHARACTERS_LIST = 'GET_CHARACTERS_LIST';
